services:
    idci_cache:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments: [%kernel.cache_dir%]

    idci_web_page_screen_shot.base64_renderer:
        class: IDCI\Bundle\WebPageScreenShotBundle\Renderer\Base64Renderer

    idci_web_page_screen_shot.file_renderer:
        class: IDCI\Bundle\WebPageScreenShotBundle\Renderer\FileRenderer

    idci_web_page_screen_shot.url_renderer:
        class: IDCI\Bundle\WebPageScreenShotBundle\Renderer\UrlRenderer
        arguments: [@router]

    idci_web_page_screen_shot.manager:
        class: IDCI\Bundle\WebPageScreenShotBundle\Service\Manager
        arguments: [%webPageScreenShotConfiguration%, @image.handling, @idci_cache, @kernel]
        calls:
            - [addRenderer, [@idci_web_page_screen_shot.url_renderer]]
            - [addRenderer, [@idci_web_page_screen_shot.file_renderer]]
            - [addRenderer, [@idci_web_page_screen_shot.base64_renderer]]